{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- include "keycloak.ingress.annotations" $ | nindent 2 }}
  name: {{ .Release.Name }}
  labels: {{ include "keycloak.labels" $ | nindent 4 }}
spec:
  rules:
  - host: {{ include "keycloak.host" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
{{- if not (empty .Values.ingress.altHostname) }}
  - host: {{ .Values.ingress.altHostname  }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
{{- end }}
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
{{- include "keycloak.tls.hosts" . | nindent 4 -}}
{{- include "keycloak.tls.secret" . | nindent 4 -}}
{{- end }}
{{- end }}
